### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "slav3@mail.com",
  "password": "101"
}

### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "100"
}

### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "user1@user.com",
  "password": "100"
}

### Регистрация
POST http://localhost:8080/taskmanager/auth/signup
Content-Type: application/json

{
  "email": "slav4@mail.com",
  "name": "slav4",
  "password": "101"
}