### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "username": "slav",
  "password": "100"
}

### Регистрация
POST http://localhost:8080/taskmanager/auth/signup
Content-Type: application/json

{
  "username": "slav4",
  "email": "slav4@mail.com",
  "password": "101"
}