### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "slav3@mail.com",
  "password": "101"
}

### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "100"
}

### Вход
POST http://localhost:8080/taskmanager/auth/signin
Content-Type: application/json

{
  "email": "user1@user.com",
  "password": "1001"
}

### Регистрация
POST http://localhost:8080/taskmanager/auth/signup
Content-Type: application/json

{
  "email": "slav7@mail.com",
  "name": "slav7",
  "password": "101"
}