### Просмотр всех комментариев постранично
GET http://localhost:8080/taskmanager/comments?page=0&size=101&authorId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM

### Просмотр всех комментариев постранично (ошибка при size>100)
GET http://localhost:8080/taskmanager/comments?page=0&size=101
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM


### Получение комментария по его id
GET http://localhost:8080/taskmanager/comments/-2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM


### Получение комментария по его id (ошибка при id<0)
GET http://localhost:8080/taskmanager/comments/3

### Создание комментария
POST http://localhost:8080/taskmanager/comments/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM
Content-Type: application/json

{
  "text": "I post this comment for task1 here",
  "taskId": 1
}

### Удаление комментария
DELETE http://localhost:8080/taskmanager/comments/delete/6
