### Просмотр всех задач постранично
GET http://localhost:8080/taskmanager/tasks?page=0&size=10&authorId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM

### Просмотр всех задач постранично
GET http://localhost:8080/taskmanager/tasks?page=0&size=10&performerId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjoyLCJlbWFpbCI6InVzZXIxQHVzZXIuY29tIiwic3ViIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE3MzIyNjg2NjAsImV4cCI6MTczMjQxMjY2MH0._7dwsEDWOM-zpA_vmAya8UTGYoMc-Hy-oi8sxEuc4IM

### Просмотр всех задач постранично (ошибка при size>100)
GET http://localhost:8080/taskmanager/tasks?page=0&size=101
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjozLCJlbWFpbCI6InNsYXZAbWFpbC5jb20iLCJzdWIiOiJzbGF2IiwiaWF0IjoxNzMyMTMyMTE5LCJleHAiOjE3MzIyNzYxMTl9.thf6OGG3PBKLr_kPr-a1OLEfydVMlrNqeMTGBarjMCQ

### Получение задачи по её id
GET http://localhost:8080/taskmanager/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX0FETUlOIn1dLCJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzIzNzMyMTMsImV4cCI6MTczMjUxNzIxM30.VNv7L6Mw6s3z4yOJ__dlALRZaupg6ZpccTZouDrD7L4

### Получение задачи по её id (ошибка при id<0)
GET http://localhost:8080/taskmanager/tasks/-1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjozLCJlbWFpbCI6InNsYXZAbWFpbC5jb20iLCJzdWIiOiJzbGF2IiwiaWF0IjoxNzMyMTMyMTE5LCJleHAiOjE3MzIyNzYxMTl9.thf6OGG3PBKLr_kPr-a1OLEfydVMlrNqeMTGBarjMCQ

### Создание задачи
POST http://localhost:8080/taskmanager/tasks/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX0FETUlOIn1dLCJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzI0NDc0NTgsImV4cCI6MTczMjU5MTQ1OH0.YrU1QUHOnFltWGTRcJZSltEEUqsCVHNzEkoSFHtND_Q
Content-Type: application/json

{
  "title": "task6_title",
  "description": "task6_desc",
  "authorId": 1,
  "performerId": 3,
  "priority": "MEDIUM",
  "status": "WAIT"
}

### Задание исполнителя для задачи
POST http://localhost:8080/taskmanager/tasks/3/performer/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjozLCJlbWFpbCI6InNsYXZAbWFpbC5jb20iLCJzdWIiOiJzbGF2IiwiaWF0IjoxNzMyMTMyMTE5LCJleHAiOjE3MzIyNzYxMTl9.thf6OGG3PBKLr_kPr-a1OLEfydVMlrNqeMTGBarjMCQ

### Редактирование задачи
PUT http://localhost:8080/taskmanager/tasks/update/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjozLCJlbWFpbCI6InNsYXZAbWFpbC5jb20iLCJzdWIiOiJzbGF2IiwiaWF0IjoxNzMyMTMyMTE5LCJleHAiOjE3MzIyNzYxMTl9.thf6OGG3PBKLr_kPr-a1OLEfydVMlrNqeMTGBarjMCQ
Content-Type: application/json

{
  "title": "task3_title33",
  "description": "task3_desc33",
  "performerId": 1,
  "priority": "HIGH",
  "status": "PROGRESS"
}

### Удаление задачи
DELETE http://localhost:8080/taskmanager/tasks/delete/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjozLCJlbWFpbCI6InNsYXZAbWFpbC5jb20iLCJzdWIiOiJzbGF2IiwiaWF0IjoxNzMyMTMyMTE5LCJleHAiOjE3MzIyNzYxMTl9.thf6OGG3PBKLr_kPr-a1OLEfydVMlrNqeMTGBarjMCQ


### Текущий пользователь
GET http://localhost:8080/taskmanager/users/info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjIsIm5hbWUiOiJST0xFX1VTRVIifV0sImlkIjo2LCJlbWFpbCI6InNsYXY0QG1haWwuY29tIiwic3ViIjoic2xhdjRAbWFpbC5jb20iLCJpYXQiOjE3MzIxNjg2MzYsImV4cCI6MTczMjMxMjYzNn0.omlVT8qdSrijf5XLQ0a7Mlu9RwItBLVJyo7fUx9hGs8

### Смена приоритета
PATCH http://localhost:8080/taskmanager/tasks/3/priority
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX0FETUlOIn1dLCJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzIzNzgwNTMsImV4cCI6MTczMjUyMjA1M30.g3Xad32y5r4NYCsE66bZs3EWjYkl5EPeYTAfN5jmke4
Content-Type: application/json

{
  "priority": "MEDIU"
}

### Смена статуса
PATCH http://localhost:8080/taskmanager/tasks/3/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6W3siaWQiOjEsIm5hbWUiOiJST0xFX0FETUlOIn1dLCJpZCI6MSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzIzNzgwNTMsImV4cCI6MTczMjUyMjA1M30.g3Xad32y5r4NYCsE66bZs3EWjYkl5EPeYTAfN5jmke4
Content-Type: application/json

{
  "status": "WAITe"
}