server:
  servlet:
    context-path: /taskmanager
spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://tm-postgres:5432/db_taskmanager?currentSchema=taskmanager
    username: slav
    password: slav
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: taskmanager
    change-log: /db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: taskmanager
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf